Wip/mos 83 onboarding page
BerkatJayaGroup/moku-app pull request #11
Opened 2021-10-25 17:41 UTC by naufaldirfq

# Description
Create sliding onboarding page

# Ticket
https://berkatjayagroup.atlassian.net/browse/MOS-86

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2021-10-25 19:45 UTC, chrsomle requested changes

2021-10-25 19:45 UTC, chrsomle commented on Moku/Services/AppState.swift
> +    @Published var hasOnboarded: Bool
bisa bgt langsung pakein userdefaults: @Published-nya diganti @AppStorage, kyk gini aja nih:
`@AppStorage(UserDefaults.hasOnboarded) var hasOnboarded = false`

2021-10-25 19:45 UTC, chrsomle commented on Moku/Services/AppState.swift
> +    init(hasOnboarded: Bool) {
karena udh dikasih default value `false` kyknya si init dikosongin sabi sih

2021-10-25 19:45 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingDataModel.swift
> +import UIKit
import uikit buat apa btw

2021-10-25 19:45 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingStepView.swift
> +            Text(data.heading).font(.title3).multilineTextAlignment(TextAlignment.center).foregroundColor(Color("PrimaryColor")).padding(.top, 300).padding(.bottom)
di enter-enter pak, jadiin multiline biar lebi readable

2021-10-25 19:45 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingStepView.swift
> +            Text(data.text).font(.body).multilineTextAlignment(TextAlignment.center)
`.multilineTextAlignment(TextAlignment.center)`
bisa dijadiin
`.multilineTextAlignment(.center)` aja

2021-10-25 19:45 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingStepView.swift
> +        VStack(alignment: .center) {
VStack tuh default alignmentnnya udh .center, jd bisa diilangin; lgsg jadiin `VStack { ... }` aja

2021-10-25 19:45 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingStepView.swift
> +            Text(data.heading).font(.title3).multilineTextAlignment(TextAlignment.center).foregroundColor(Color("PrimaryColor")).padding(.top, 300).padding(.bottom)
kyknya `Color("PrimaryColor")` udh sering bgt muncul, bikin `AppColor.swift` di folder Constants aja kali ya?

2021-10-25 19:45 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingView.swift
> +                .foregroundColor(Color("PrimaryColor"))
nih di file ini muncul byk bgt

2021-10-25 19:45 UTC, chrsomle commented on Podfile.lock
> +COCOAPODS: 1.10.2
cocoapodsnya di lu downgrade nih, kyknya perlu lu update bang

2021-10-25 19:45 UTC, chrsomle commented on Moku/MokuApp.swift
> +//                GoogleMapView(coordinate: $userLocation.coordinate) {
ohiya maap, ni commentsnya ntr gw yg beresin di branchh gw

2021-10-25 19:45 UTC, chrsomle commented on Moku/MokuApp.swift
> +//                GoogleMapView(coordinate: $userLocation.coordinate) {
belom di rapiin

2021-10-25 19:48 UTC, chrsomle commented on Moku/Services/AppState.swift
> +    @Published var hasOnboarded: Bool
btw itu gw bikin `UserDefaults.swift` di folder Constants, gini:
`
struct UserDefaults {
    static let hasOnboarded = "has_onboarded"
}
`

2021-10-26 03:26 UTC, naufaldirfq commented on Moku/Views/Onboarding/OnboardingStepView.swift
> +            Text(data.heading).font(.title3).multilineTextAlignment(TextAlignment.center).foregroundColor(Color("PrimaryColor")).padding(.top, 300).padding(.bottom)
> kyknya `Color("PrimaryColor")` udh sering bgt muncul, bikin `AppColor.swift` di folder Constants aja kali ya?

ini katanya @albertusfavian udah bikin di branch lain. ya kan ya? wkwkwk

2021-10-26 03:27 UTC, naufaldirfq commented on Moku/Views/Onboarding/OnboardingDataModel.swift
> +import UIKit
kepencet

2021-10-26 03:28 UTC, naufaldirfq commented on Moku/Views/Onboarding/OnboardingView.swift
> +                .foregroundColor(Color("PrimaryColor"))
kyknya dibikin reusable component aja kali ya?

2021-10-26 03:33 UTC, naufaldirfq commented on Moku/Services/AppState.swift
> +    @Published var hasOnboarded: Bool
> btw itu gw bikin `UserDefaults.swift` di folder Constants, gini:
> `struct UserDefaults { static let hasOnboarded = "has_onboarded" }`

gua gak nemu filenya nih. ini di branch mana ya kris?

2021-10-26 04:45 UTC, chrsomle commented on Moku/Services/AppState.swift
> +    @Published var hasOnboarded: Bool
ohh emg blm pal, lu yg bikin aha

2021-10-26 04:46 UTC, chrsomle approved these changes

2021-10-26 04:47 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingView.swift
> +                .foregroundColor(Color("PrimaryColor"))
eh mksd gw si Color(...) yg munculnya sering bgt

2021-10-26 04:47 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingView.swift
> +                .foregroundColor(Color("PrimaryColor"))
masukin ke AppColor

2021-10-26 04:47 UTC, chrsomle commented on Moku/Views/Onboarding/OnboardingStepView.swift
> +            Text(data.heading).font(.title3).multilineTextAlignment(TextAlignment.center).foregroundColor(Color("PrimaryColor")).padding(.top, 300).padding(.bottom)
Kalo udh, merge sabi sih ntr paling dibenerin di branch si albert

2021-10-26 04:48 UTC, chrsomle commented
eh keren bgt btw ada checklistnya skrg

2021-10-26 07:51 UTC, merged