Feature/mos 58 get workshop available time backend
BerkatJayaGroup/moku-app pull request #52
Opened 2021-11-09 06:45 UTC by albertusfavian

# Description
Update Available time for Workshop and disabled fully booking on that time

# Ticket
https://berkatjayagroup.atlassian.net/browse/MOS-58?atlOrigin=eyJpIjoiZGRkMDhhOGQ3YjU3NDgxNDkzY2VmMTMyNWIyMjg5MmUiLCJwIjoiaiJ9

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2021-11-10 23:37 UTC, zeinrezky requested changes
Please review and do necessary revision.

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Bengkel/PengaturanHargaBengkel.swift
>              maxPrice: max
If this are static, put it under constant, so then it became more easier to maintain, otherwise, should be ok.

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Bengkel/PengaturanHargaBengkel.swift
>              var mekBaru = Mekanik(name: mech.name)
naming should be standardize using english wording. Please change all the wordings inside the project to english.

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Bengkel/PengaturanHargaBengkel.swift
>                  storageService.upload(image: photo, path: mekBaru.id)
This upload process should run under new background thread, to avoid lagging.

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Bengkel/PengaturanHargaBengkel.swift
> +            } else {
Unnecessary else condition, should change to guard let on the first optional condition, then you don't need this else.

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Customer/Extentions/DateExtention.swift
>              let lastIndex = 7 + (7 - hari)
What this is formula about? Is 7 magic number? what does it mean? Put 7 as constant with clear naming convention so easily manage in the future development

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Customer/Extentions/DateExtention.swift
> +                guard let fullDate = calendar.date(byAdding: DateComponents(day: number), to: Date()) else { continue }
Same code as inside IF

2021-11-10 23:37 UTC, zeinrezky commented on Moku/Repositories/OrderRepository.swift
> +                self.filteredOrders = order
This shouldn't under main thread, should be background thread.

2021-11-11 03:13 UTC, chrsomle commented on Moku/Bengkel/PengaturanHargaBengkel.swift
>              maxPrice: max
noted kak

2021-11-11 03:21 UTC, chrsomle commented on Moku/Bengkel/PengaturanHargaBengkel.swift
>              var mekBaru = Mekanik(name: mech.name)
okehh will start using english and will do codebase cleanup after v1 kak

2021-11-11 03:25 UTC, chrsomle commented on Moku/Bengkel/PengaturanHargaBengkel.swift
>                  storageService.upload(image: photo, path: mekBaru.id)
`
// Upload the image
        if let data = data, let storage = storageRef {
            DispatchQueue.global(qos: .background).async {
                storage.putData(data, metadata: metadata, completion: completion)
            }
        }
`

kalo ke background thread gini aja kan kak?

2021-11-11 04:07 UTC, chrsomle approved these changes

2021-11-11 10:44 UTC, merged